// <auto-generated />
using GymFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFinal.Migrations
{
    [DbContext(typeof(GimnasioContext))]
    partial class GimnasioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActividadEmpleado", b =>
                {
                    b.Property<int>("ActividadesCodActividad")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadosLegajo")
                        .HasColumnType("int");

                    b.HasKey("ActividadesCodActividad", "EmpleadosLegajo");

                    b.HasIndex("EmpleadosLegajo");

                    b.ToTable("EmpleadoActividad", (string)null);
                });

            modelBuilder.Entity("GymFinal.Models.Actividad", b =>
                {
                    b.Property<int>("CodActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodActividad"));

                    b.Property<int>("DuracionMins")
                        .HasColumnType("int");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodActividad");

                    b.HasIndex("IdSede");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("GymFinal.Models.Empleado", b =>
                {
                    b.Property<int>("Legajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Legajo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Legajo");

                    b.HasIndex("IdSede");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GymFinal.Models.Plan", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<string>("DescripcionPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdPlan");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("GymFinal.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSede");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("GymFinal.Models.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSocio"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocio");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdSede");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("ActividadEmpleado", b =>
                {
                    b.HasOne("GymFinal.Models.Actividad", null)
                        .WithMany()
                        .HasForeignKey("ActividadesCodActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinal.Models.Empleado", null)
                        .WithMany()
                        .HasForeignKey("EmpleadosLegajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymFinal.Models.Actividad", b =>
                {
                    b.HasOne("GymFinal.Models.Sede", "Sede")
                        .WithMany("Actividades")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("GymFinal.Models.Empleado", b =>
                {
                    b.HasOne("GymFinal.Models.Sede", "Sede")
                        .WithMany("Empleados")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("GymFinal.Models.Socio", b =>
                {
                    b.HasOne("GymFinal.Models.Plan", "Plan")
                        .WithMany("Socios")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinal.Models.Sede", "Sede")
                        .WithMany("Socios")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("GymFinal.Models.Plan", b =>
                {
                    b.Navigation("Socios");
                });

            modelBuilder.Entity("GymFinal.Models.Sede", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Empleados");

                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
